"""add country to channel table

Revision ID: 131736cdd610
Revises: 3f2180fd8cb7
Create Date: 2025-11-28 19:37:52.423440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131736cdd610'
down_revision: Union[str, None] = '3f2180fd8cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'country')
    # ### end Alembic commands ###
