"""initial

Revision ID: 3a6a2c5e7a70
Revises: 
Create Date: 2025-10-20 22:08:18.077252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a6a2c5e7a70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_title', sa.String(length=300), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('duration_iso', sa.String(length=32), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index('ix_videos_channel_id', 'videos', ['channel_id'], unique=False)
    op.create_index('ix_videos_published_at', 'videos', ['published_at'], unique=False)
    op.create_table('rec_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('source_video_id', sa.Text(), nullable=True),
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rec_events')
    op.drop_index('ix_videos_published_at', table_name='videos')
    op.drop_index('ix_videos_channel_id', table_name='videos')
    op.drop_table('videos')
    op.drop_table('categories')
    # ### end Alembic commands ###
