"""Change tags column to ARRAY type

Revision ID: 72bcf4dff576
Revises: 46e03e9e0bdf
Create Date: 2025-10-18 23:44:05.222634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72bcf4dff576'
down_revision: Union[str, None] = '46e03e9e0bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('videos', 'tags_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('videos', 'tags')
    # ### end Alembic commands ###
