"""add foreign key from videos to channels

Revision ID: debb984964ba
Revises: 131736cdd610
Create Date: 2025-11-28 19:39:49.899388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debb984964ba'
down_revision: Union[str, None] = '131736cdd610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'videos', 'channels', ['channel_id'], ['channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    # ### end Alembic commands ###
